name: Strain Data Pipeline

on:
  schedule:
    # Runs daily at 3:00 AM UTC
    - cron: '0 3 * * *'
  workflow_dispatch: # Allows manual triggering from GitHub UI

permissions:
  contents: write

jobs:
  update-strains:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install
          npm install node-fetch node-html-parser csv-parse @supabase/supabase-js dotenv

      - name: Run full pipeline
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          node tools/full_pipeline.mjs | tee pipeline.log

      - name: Update pipeline history JSON
        run: |
          node scripts/update_pipeline_history.mjs

      - name: Commit and push history
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add reports/pipeline-history.json
          if git diff --cached --quiet; then
            echo "No history changes to commit"
          else
            git commit -m "chore(pipeline): update history [skip ci]"
            git push
          fi

      - name: Upload pipeline logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-logs
          path: |
            backend/data/import_report.json
            pipeline.log
          retention-days: 30
